-- MySQL Script generated by MySQL Workbench
-- Tue Nov 13 11:28:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema group1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema group1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `group1` DEFAULT CHARACTER SET utf8 ;
USE `group1` ;

-- -----------------------------------------------------
-- Table `group1`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`subject` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `subject_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_subject_id_idx` (`subject_id` ASC),
  CONSTRAINT `category_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `group1`.`subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`material` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `material_category_id_idx` (`category_id` ASC),
  CONSTRAINT `material_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `group1`.`category` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`material_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`material_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `material_id` INT(11) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `material_item_material_id_idx` (`material_id` ASC),
  CONSTRAINT `material_item_material_id`
    FOREIGN KEY (`material_id`)
    REFERENCES `group1`.`material` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`quiz` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `material_id` INT(11) NULL DEFAULT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `quiz_material_id_idx` (`material_id` ASC),
  INDEX `quiz_category_id_idx` (`category_id` ASC),
  CONSTRAINT `quiz_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `group1`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quiz_material_id`
    FOREIGN KEY (`material_id`)
    REFERENCES `group1`.`material` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`questions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `quiz_id` INT(11) NOT NULL,
  `difficulty` INT(11) NOT NULL,
  `material_item_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `questions_quiz_id_idx` (`quiz_id` ASC),
  INDEX `questions_material_item_id_idx` (`material_item_id` ASC),
  CONSTRAINT `questions_material_item_id`
    FOREIGN KEY (`material_item_id`)
    REFERENCES `group1`.`material_item` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `questions_quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `group1`.`quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`answer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question_id` INT(11) NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  `correct_answer` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `answer_question_id_idx` (`question_id` ASC),
  CONSTRAINT `answer_question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `group1`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`quiz_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`quiz_instance` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `quiz_id` INT(11) NOT NULL,
  `result` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `quiz_instance_user_id_idx` (`user_id` ASC),
  INDEX `quiz_instance_quiz_id_idx` (`quiz_id` ASC),
  CONSTRAINT `quiz_instance_quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `group1`.`quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `quiz_instance_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `group1`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`answer_given`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`answer_given` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question_id` INT(11) NOT NULL,
  `answer_id` INT(11) NOT NULL,
  `quiz_instance` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `answer_given_question_id_idx` (`question_id` ASC),
  INDEX `answer_given_answer_id_idx` (`answer_id` ASC),
  INDEX `answer_given_quiz_instance_idx` (`quiz_instance` ASC),
  CONSTRAINT `answer_given_answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `group1`.`answer` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_given_question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `group1`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_given_quiz_instance`
    FOREIGN KEY (`quiz_instance`)
    REFERENCES `group1`.`quiz_instance` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group1`.`stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`stats` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `subject_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `points` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `stats_subject_id_idx` (`subject_id` ASC),
  INDEX `stats_user_id_idx` (`user_id` ASC),
  CONSTRAINT `stats_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `group1`.`subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `stats_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `group1`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
