-- MySQL Script generated by MySQL Workbench
-- Mon Nov 12 13:19:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema group1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema group1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `group1` DEFAULT CHARACTER SET utf8 ;
USE `group1` ;

-- -----------------------------------------------------
-- Table `group1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`subject` (
  `id` INT NOT NULL,
  `subject` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`category` (
  `id` INT NOT NULL,
  `subject_id` INT NULL,
  `category` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `category_subject_id_idx` (`subject_id` ASC),
  CONSTRAINT `category_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `group1`.`subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`material` (
  `id` INT NOT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `material_category_id_idx` (`category_id` ASC),
  CONSTRAINT `material_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `group1`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`material_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`material_item` (
  `id` INT NOT NULL,
  `material_id` INT NULL,
  `content` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `material_item_material_id_idx` (`material_id` ASC),
  CONSTRAINT `material_item_material_id`
    FOREIGN KEY (`material_id`)
    REFERENCES `group1`.`material` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `subject` VARCHAR(45) NULL,
  `difficulty` INT NULL,
  `material_item_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `questions_material_item_id_idx` (`material_item_id` ASC),
  CONSTRAINT `questions_material_item_id`
    FOREIGN KEY (`material_item_id`)
    REFERENCES `group1`.`material_item` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`answer` (
  `id` INT NOT NULL,
  `question_id` INT NULL,
  `answer` VARCHAR(255) NULL,
  `correct_answer` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `question_id_idx` (`question_id` ASC),
  CONSTRAINT `answer_question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `group1`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`stats` (
  `id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `points` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `stats_subject_id_idx` (`subject_id` ASC),
  INDEX `stats_user_id_idx` (`user_id` ASC),
  CONSTRAINT `stats_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `group1`.`subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `stats_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `group1`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`quiz` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `quiz_instance` VARCHAR(45) NULL,
  `answer_given` VARCHAR(45) NULL,
  `material_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `quiz_material_id_idx` (`material_id` ASC),
  CONSTRAINT `quiz_material_id`
    FOREIGN KEY (`material_id`)
    REFERENCES `group1`.`material` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`quiz_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`quiz_instance` (
  `id` INT NOT NULL,
  `user_id` INT NULL,
  `quiz_id` INT NULL,
  `result` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `quiz_instance_user_id_idx` (`user_id` ASC),
  INDEX `quiz_instance_quiz_id_idx` (`quiz_id` ASC),
  CONSTRAINT `quiz_instance_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `group1`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `quiz_instance_quiz_id`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `group1`.`quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group1`.`answer_given`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group1`.`answer_given` (
  `id` INT NOT NULL,
  `question_id` INT NULL,
  `answer_id` INT NULL,
  `quiz_instance` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `answer_given_question_id_idx` (`question_id` ASC),
  INDEX `answer_given_answer_id_idx` (`answer_id` ASC),
  INDEX `answer_given_quiz_instance_idx` (`quiz_instance` ASC),
  CONSTRAINT `answer_given_question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `group1`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_given_answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `group1`.`answer` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_given_quiz_instance`
    FOREIGN KEY (`quiz_instance`)
    REFERENCES `group1`.`quiz_instance` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
